#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UTubeSave.Droid.Resource", IsApplication=true)]

namespace UTubeSave.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::HockeyApp.Resource.Color.hockeyapp_background_header = global::UTubeSave.Droid.Resource.Color.hockeyapp_background_header;
			global::HockeyApp.Resource.Color.hockeyapp_background_light = global::UTubeSave.Droid.Resource.Color.hockeyapp_background_light;
			global::HockeyApp.Resource.Color.hockeyapp_background_white = global::UTubeSave.Droid.Resource.Color.hockeyapp_background_white;
			global::HockeyApp.Resource.Color.hockeyapp_button_background = global::UTubeSave.Droid.Resource.Color.hockeyapp_button_background;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_pressed = global::UTubeSave.Droid.Resource.Color.hockeyapp_button_background_pressed;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_selected = global::UTubeSave.Droid.Resource.Color.hockeyapp_button_background_selected;
			global::HockeyApp.Resource.Color.hockeyapp_text_black = global::UTubeSave.Droid.Resource.Color.hockeyapp_text_black;
			global::HockeyApp.Resource.Color.hockeyapp_text_light = global::UTubeSave.Droid.Resource.Color.hockeyapp_text_light;
			global::HockeyApp.Resource.Color.hockeyapp_text_normal = global::UTubeSave.Droid.Resource.Color.hockeyapp_text_normal;
			global::HockeyApp.Resource.Color.hockeyapp_text_white = global::UTubeSave.Droid.Resource.Color.hockeyapp_text_white;
			global::HockeyApp.Resource.Drawable.hockeyapp_btn_background = global::UTubeSave.Droid.Resource.Drawable.hockeyapp_btn_background;
			global::HockeyApp.Resource.Id.button_add_response = global::UTubeSave.Droid.Resource.Id.button_add_response;
			global::HockeyApp.Resource.Id.button_attachment = global::UTubeSave.Droid.Resource.Id.button_attachment;
			global::HockeyApp.Resource.Id.button_login = global::UTubeSave.Droid.Resource.Id.button_login;
			global::HockeyApp.Resource.Id.button_refresh = global::UTubeSave.Droid.Resource.Id.button_refresh;
			global::HockeyApp.Resource.Id.button_send = global::UTubeSave.Droid.Resource.Id.button_send;
			global::HockeyApp.Resource.Id.button_update = global::UTubeSave.Droid.Resource.Id.button_update;
			global::HockeyApp.Resource.Id.input_email = global::UTubeSave.Droid.Resource.Id.input_email;
			global::HockeyApp.Resource.Id.input_message = global::UTubeSave.Droid.Resource.Id.input_message;
			global::HockeyApp.Resource.Id.input_name = global::UTubeSave.Droid.Resource.Id.input_name;
			global::HockeyApp.Resource.Id.input_password = global::UTubeSave.Droid.Resource.Id.input_password;
			global::HockeyApp.Resource.Id.input_subject = global::UTubeSave.Droid.Resource.Id.input_subject;
			global::HockeyApp.Resource.Id.label_author = global::UTubeSave.Droid.Resource.Id.label_author;
			global::HockeyApp.Resource.Id.label_date = global::UTubeSave.Droid.Resource.Id.label_date;
			global::HockeyApp.Resource.Id.label_last_updated = global::UTubeSave.Droid.Resource.Id.label_last_updated;
			global::HockeyApp.Resource.Id.label_message = global::UTubeSave.Droid.Resource.Id.label_message;
			global::HockeyApp.Resource.Id.label_text = global::UTubeSave.Droid.Resource.Id.label_text;
			global::HockeyApp.Resource.Id.label_title = global::UTubeSave.Droid.Resource.Id.label_title;
			global::HockeyApp.Resource.Id.label_version = global::UTubeSave.Droid.Resource.Id.label_version;
			global::HockeyApp.Resource.Id.list_attachments = global::UTubeSave.Droid.Resource.Id.list_attachments;
			global::HockeyApp.Resource.Id.list_feedback_messages = global::UTubeSave.Droid.Resource.Id.list_feedback_messages;
			global::HockeyApp.Resource.Id.text_headline = global::UTubeSave.Droid.Resource.Id.text_headline;
			global::HockeyApp.Resource.Id.view_header = global::UTubeSave.Droid.Resource.Id.view_header;
			global::HockeyApp.Resource.Id.web_update_details = global::UTubeSave.Droid.Resource.Id.web_update_details;
			global::HockeyApp.Resource.Id.wrapper_attachments = global::UTubeSave.Droid.Resource.Id.wrapper_attachments;
			global::HockeyApp.Resource.Id.wrapper_feedback = global::UTubeSave.Droid.Resource.Id.wrapper_feedback;
			global::HockeyApp.Resource.Id.wrapper_feedback_scroll = global::UTubeSave.Droid.Resource.Id.wrapper_feedback_scroll;
			global::HockeyApp.Resource.Id.wrapper_messages = global::UTubeSave.Droid.Resource.Id.wrapper_messages;
			global::HockeyApp.Resource.Id.wrapper_messages_buttons = global::UTubeSave.Droid.Resource.Id.wrapper_messages_buttons;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_expiry_info = global::UTubeSave.Droid.Resource.Layout.hockeyapp_activity_expiry_info;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_feedback = global::UTubeSave.Droid.Resource.Layout.hockeyapp_activity_feedback;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_login = global::UTubeSave.Droid.Resource.Layout.hockeyapp_activity_login;
			global::HockeyApp.Resource.Layout.hockeyapp_fragment_update = global::UTubeSave.Droid.Resource.Layout.hockeyapp_fragment_update;
			global::HockeyApp.Resource.Layout.hockeyapp_view_feedback_message = global::UTubeSave.Droid.Resource.Layout.hockeyapp_view_feedback_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_app_name_fallback = global::UTubeSave.Droid.Resource.String.hockeyapp_crash_dialog_app_name_fallback;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_message = global::UTubeSave.Droid.Resource.String.hockeyapp_crash_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_negative_button = global::UTubeSave.Droid.Resource.String.hockeyapp_crash_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_neutral_button = global::UTubeSave.Droid.Resource.String.hockeyapp_crash_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_positive_button = global::UTubeSave.Droid.Resource.String.hockeyapp_crash_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_title = global::UTubeSave.Droid.Resource.String.hockeyapp_crash_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_message = global::UTubeSave.Droid.Resource.String.hockeyapp_dialog_error_message;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_title = global::UTubeSave.Droid.Resource.String.hockeyapp_dialog_error_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_positive_button = global::UTubeSave.Droid.Resource.String.hockeyapp_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_message = global::UTubeSave.Droid.Resource.String.hockeyapp_download_failed_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_negative_button = global::UTubeSave.Droid.Resource.String.hockeyapp_download_failed_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_positive_button = global::UTubeSave.Droid.Resource.String.hockeyapp_download_failed_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_title = global::UTubeSave.Droid.Resource.String.hockeyapp_download_failed_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_error_install_form_unknown_sources_disabled = global::UTubeSave.Droid.Resource.String.hockeyapp_error_install_form_unknown_sources_disabled;
			global::HockeyApp.Resource.String.hockeyapp_error_no_external_storage_permission = global::UTubeSave.Droid.Resource.String.hockeyapp_error_no_external_storage_permission;
			global::HockeyApp.Resource.String.hockeyapp_error_no_network_message = global::UTubeSave.Droid.Resource.String.hockeyapp_error_no_network_message;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_text = global::UTubeSave.Droid.Resource.String.hockeyapp_expiry_info_text;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_title = global::UTubeSave.Droid.Resource.String.hockeyapp_expiry_info_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_file = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_attach_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_picture = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_attach_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_added = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_attachment_added;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_button_text = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_attachment_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_error = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_attachment_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_loading = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_attachment_loading;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_remove_description = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_attachment_remove_description;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_removed = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_attachment_removed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint_required = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_email_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_feedback_fetching_feedback_text = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_fetching_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_last_updated_text = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_last_updated_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_max_attachments_allowed = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_max_attachments_allowed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_message_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint_required = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_message_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_name_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint_required = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_name_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_feedback_new_answer_notification_message = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_new_answer_notification_message;
			global::HockeyApp.Resource.String.hockeyapp_feedback_notification_channel = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_notification_channel;
			global::HockeyApp.Resource.String.hockeyapp_feedback_notification_title = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_notification_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_refresh_button_text = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_refresh_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_response_button_text = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_response_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_screenshot_fail = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_screenshot_fail;
			global::HockeyApp.Resource.String.hockeyapp_feedback_screenshot_notification_message = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_screenshot_notification_message;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_file = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_select_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_picture = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_select_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_button_text = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_send_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_generic_error = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_send_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_network_error = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_send_network_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sending_feedback_text = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_sending_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sent_toast = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_sent_toast;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_subject_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint_required = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_subject_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_feedback_title = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_empty = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_validate_email_empty;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_error = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_validate_email_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_name_error = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_validate_name_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_subject_error = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_validate_subject_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_text_error = global::UTubeSave.Droid.Resource.String.hockeyapp_feedback_validate_text_error;
			global::HockeyApp.Resource.String.hockeyapp_login_email_hint_required = global::UTubeSave.Droid.Resource.String.hockeyapp_login_email_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text = global::UTubeSave.Droid.Resource.String.hockeyapp_login_headline_text;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text_email_only = global::UTubeSave.Droid.Resource.String.hockeyapp_login_headline_text_email_only;
			global::HockeyApp.Resource.String.hockeyapp_login_login_button_text = global::UTubeSave.Droid.Resource.String.hockeyapp_login_login_button_text;
			global::HockeyApp.Resource.String.hockeyapp_login_missing_credentials_toast = global::UTubeSave.Droid.Resource.String.hockeyapp_login_missing_credentials_toast;
			global::HockeyApp.Resource.String.hockeyapp_login_password_hint_required = global::UTubeSave.Droid.Resource.String.hockeyapp_login_password_hint_required;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_message = global::UTubeSave.Droid.Resource.String.hockeyapp_paint_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_negative_button = global::UTubeSave.Droid.Resource.String.hockeyapp_paint_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_neutral_button = global::UTubeSave.Droid.Resource.String.hockeyapp_paint_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_positive_button = global::UTubeSave.Droid.Resource.String.hockeyapp_paint_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_indicator_toast = global::UTubeSave.Droid.Resource.String.hockeyapp_paint_indicator_toast;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_clear = global::UTubeSave.Droid.Resource.String.hockeyapp_paint_menu_clear;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_save = global::UTubeSave.Droid.Resource.String.hockeyapp_paint_menu_save;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_undo = global::UTubeSave.Droid.Resource.String.hockeyapp_paint_menu_undo;
			global::HockeyApp.Resource.String.hockeyapp_update_already_installed = global::UTubeSave.Droid.Resource.String.hockeyapp_update_already_installed;
			global::HockeyApp.Resource.String.hockeyapp_update_button = global::UTubeSave.Droid.Resource.String.hockeyapp_update_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_message = global::UTubeSave.Droid.Resource.String.hockeyapp_update_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_negative_button = global::UTubeSave.Droid.Resource.String.hockeyapp_update_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_positive_button = global::UTubeSave.Droid.Resource.String.hockeyapp_update_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_title = global::UTubeSave.Droid.Resource.String.hockeyapp_update_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_update_loading = global::UTubeSave.Droid.Resource.String.hockeyapp_update_loading;
			global::HockeyApp.Resource.String.hockeyapp_update_mandatory_toast = global::UTubeSave.Droid.Resource.String.hockeyapp_update_mandatory_toast;
			global::HockeyApp.Resource.String.hockeyapp_update_newest_version = global::UTubeSave.Droid.Resource.String.hockeyapp_update_newest_version;
			global::HockeyApp.Resource.String.hockeyapp_update_no_info = global::UTubeSave.Droid.Resource.String.hockeyapp_update_no_info;
			global::HockeyApp.Resource.String.hockeyapp_update_restore = global::UTubeSave.Droid.Resource.String.hockeyapp_update_restore;
			global::HockeyApp.Resource.String.hockeyapp_update_title = global::UTubeSave.Droid.Resource.String.hockeyapp_update_title;
			global::HockeyApp.Resource.String.hockeyapp_update_unknown_size = global::UTubeSave.Droid.Resource.String.hockeyapp_update_unknown_size;
			global::HockeyApp.Resource.String.hockeyapp_update_version = global::UTubeSave.Droid.Resource.String.hockeyapp_update_version;
			global::HockeyApp.Resource.String.hockeyapp_update_version_details_label = global::UTubeSave.Droid.Resource.String.hockeyapp_update_version_details_label;
			global::HockeyApp.Resource.String.library_name = global::UTubeSave.Droid.Resource.String.library_name;
			global::HockeyApp.Resource.Style.HockeyApp_ButtonStyle = global::UTubeSave.Droid.Resource.Style.HockeyApp_ButtonStyle;
			global::HockeyApp.Resource.Style.HockeyApp_EditTextStyle = global::UTubeSave.Droid.Resource.Style.HockeyApp_EditTextStyle;
			global::HockeyApp.Resource.Style.HockeyApp_SingleLineInputStyle = global::UTubeSave.Droid.Resource.Style.HockeyApp_SingleLineInputStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int adSize = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int adSizes = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int adUnitId = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010010
			public const int font = 2130771984;
			
			// aapt resource value: 0x7f010009
			public const int fontProviderAuthority = 2130771977;
			
			// aapt resource value: 0x7f01000c
			public const int fontProviderCerts = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int fontProviderFetchStrategy = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int fontProviderFetchTimeout = 2130771982;
			
			// aapt resource value: 0x7f01000a
			public const int fontProviderPackage = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int fontProviderQuery = 2130771979;
			
			// aapt resource value: 0x7f01000f
			public const int fontStyle = 2130771983;
			
			// aapt resource value: 0x7f010011
			public const int fontWeight = 2130771985;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int abc_action_bar_embed_tabs = 2131230720;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060019
			public const int common_google_signin_btn_text_dark = 2131099673;
			
			// aapt resource value: 0x7f060000
			public const int common_google_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_signin_btn_text_dark_disabled = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_signin_btn_text_dark_focused = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_signin_btn_text_dark_pressed = 2131099651;
			
			// aapt resource value: 0x7f06001a
			public const int common_google_signin_btn_text_light = 2131099674;
			
			// aapt resource value: 0x7f060004
			public const int common_google_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_signin_btn_text_light_disabled = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_signin_btn_text_light_focused = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_signin_btn_text_light_pressed = 2131099655;
			
			// aapt resource value: 0x7f06001b
			public const int common_google_signin_btn_tint = 2131099675;
			
			// aapt resource value: 0x7f06000f
			public const int hockeyapp_background_header = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int hockeyapp_background_light = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int hockeyapp_background_white = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int hockeyapp_button_background = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int hockeyapp_button_background_pressed = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int hockeyapp_button_background_selected = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int hockeyapp_text_black = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int hockeyapp_text_light = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int hockeyapp_text_normal = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int hockeyapp_text_white = 2131099672;
			
			// aapt resource value: 0x7f06000b
			public const int notification_action_color_filter = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int notification_icon_bg_color = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int notification_material_background_media_default_color = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int primary_text_default_material_dark = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int ripple_material_light = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int secondary_text_default_material_dark = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int secondary_text_default_material_light = 2131099662;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090004
			public const int compat_button_inset_horizontal_material = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int compat_button_inset_vertical_material = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int compat_button_padding_horizontal_material = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int compat_button_padding_vertical_material = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int compat_control_corner_material = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int notification_action_icon_size = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int notification_action_text_size = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int notification_big_circle_margin = 2131296267;
			
			// aapt resource value: 0x7f090001
			public const int notification_content_margin_start = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int notification_large_icon_height = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int notification_large_icon_width = 2131296269;
			
			// aapt resource value: 0x7f090002
			public const int notification_main_column_padding_top = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int notification_media_narrow_margin = 2131296259;
			
			// aapt resource value: 0x7f09000e
			public const int notification_right_icon_size = 2131296270;
			
			// aapt resource value: 0x7f090000
			public const int notification_right_side_padding_top = 2131296256;
			
			// aapt resource value: 0x7f09000f
			public const int notification_small_icon_background_padding = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int notification_small_icon_size_as_large = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int notification_subtext_size = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int notification_top_pad = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int notification_top_pad_large_text = 2131296275;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_disabled = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_text_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_normal_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_normal_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int googleg_disabled_color_18 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int googleg_standard_color_18 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int hockeyapp_btn_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_subscriptions_black_36dp = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_subscriptions_white_36dp = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_sync_black_36dp = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_sync_white_36dp = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int notification_action_background = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int notification_bg = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int notification_bg_low = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int notification_bg_low_normal = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int notification_bg_low_pressed = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int notification_bg_normal = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int notification_bg_normal_pressed = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int notification_icon_background = 2130837537;
			
			// aapt resource value: 0x7f02002b
			public const int notification_template_icon_bg = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int notification_template_icon_low_bg = 2130837548;
			
			// aapt resource value: 0x7f020022
			public const int notification_tile_bg = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int notify_panel_notification_icon_bg = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int RedCircleWithShadow = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int RedCircleWithSmallShadow = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int SelectorCircleButton = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int SelectorDownloadsButton = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int SelectorSyncButton = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int UTubeLogo = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int VideoLogo = 2130837546;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0044
			public const int action0 = 2131361860;
			
			// aapt resource value: 0x7f0a0041
			public const int action_container = 2131361857;
			
			// aapt resource value: 0x7f0a0048
			public const int action_divider = 2131361864;
			
			// aapt resource value: 0x7f0a0042
			public const int action_image = 2131361858;
			
			// aapt resource value: 0x7f0a0043
			public const int action_text = 2131361859;
			
			// aapt resource value: 0x7f0a0052
			public const int actions = 2131361874;
			
			// aapt resource value: 0x7f0a0040
			public const int activityBar = 2131361856;
			
			// aapt resource value: 0x7f0a003e
			public const int adView = 2131361854;
			
			// aapt resource value: 0x7f0a0005
			public const int adjust_height = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int adjust_width = 2131361798;
			
			// aapt resource value: 0x7f0a000e
			public const int async = 2131361806;
			
			// aapt resource value: 0x7f0a0017
			public const int audioBitradeSpinner = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int audioTypeSpinner = 2131361816;
			
			// aapt resource value: 0x7f0a000b
			public const int auto = 2131361803;
			
			// aapt resource value: 0x7f0a003c
			public const int availabilityView = 2131361852;
			
			// aapt resource value: 0x7f0a000f
			public const int blocking = 2131361807;
			
			// aapt resource value: 0x7f0a0027
			public const int button_add_response = 2131361831;
			
			// aapt resource value: 0x7f0a0022
			public const int button_attachment = 2131361826;
			
			// aapt resource value: 0x7f0a002c
			public const int button_login = 2131361836;
			
			// aapt resource value: 0x7f0a0028
			public const int button_refresh = 2131361832;
			
			// aapt resource value: 0x7f0a0023
			public const int button_send = 2131361827;
			
			// aapt resource value: 0x7f0a0030
			public const int button_update = 2131361840;
			
			// aapt resource value: 0x7f0a0045
			public const int cancel_action = 2131361861;
			
			// aapt resource value: 0x7f0a004d
			public const int chronometer = 2131361869;
			
			// aapt resource value: 0x7f0a003f
			public const int contentView = 2131361855;
			
			// aapt resource value: 0x7f0a003a
			public const int currentDownloads = 2131361850;
			
			// aapt resource value: 0x7f0a000c
			public const int dark = 2131361804;
			
			// aapt resource value: 0x7f0a0014
			public const int downloadProgressBar = 2131361812;
			
			// aapt resource value: 0x7f0a0054
			public const int end_padder = 2131361876;
			
			// aapt resource value: 0x7f0a0010
			public const int forever = 2131361808;
			
			// aapt resource value: 0x7f0a004f
			public const int icon = 2131361871;
			
			// aapt resource value: 0x7f0a0053
			public const int icon_group = 2131361875;
			
			// aapt resource value: 0x7f0a0008
			public const int icon_only = 2131361800;
			
			// aapt resource value: 0x7f0a004e
			public const int info = 2131361870;
			
			// aapt resource value: 0x7f0a001e
			public const int input_email = 2131361822;
			
			// aapt resource value: 0x7f0a0020
			public const int input_message = 2131361824;
			
			// aapt resource value: 0x7f0a001d
			public const int input_name = 2131361821;
			
			// aapt resource value: 0x7f0a002b
			public const int input_password = 2131361835;
			
			// aapt resource value: 0x7f0a001f
			public const int input_subject = 2131361823;
			
			// aapt resource value: 0x7f0a0011
			public const int italic = 2131361809;
			
			// aapt resource value: 0x7f0a0032
			public const int label_author = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int label_date = 2131361843;
			
			// aapt resource value: 0x7f0a0025
			public const int label_last_updated = 2131361829;
			
			// aapt resource value: 0x7f0a001a
			public const int label_message = 2131361818;
			
			// aapt resource value: 0x7f0a0034
			public const int label_text = 2131361844;
			
			// aapt resource value: 0x7f0a002e
			public const int label_title = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int label_version = 2131361839;
			
			// aapt resource value: 0x7f0a000d
			public const int light = 2131361805;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a0035
			public const int list_attachments = 2131361845;
			
			// aapt resource value: 0x7f0a0029
			public const int list_feedback_messages = 2131361833;
			
			// aapt resource value: 0x7f0a0047
			public const int media_actions = 2131361863;
			
			// aapt resource value: 0x7f0a0057
			public const int noVideoView = 2131361879;
			
			// aapt resource value: 0x7f0a0007
			public const int none = 2131361799;
			
			// aapt resource value: 0x7f0a0012
			public const int normal = 2131361810;
			
			// aapt resource value: 0x7f0a0051
			public const int notification_background = 2131361873;
			
			// aapt resource value: 0x7f0a004a
			public const int notification_main_column = 2131361866;
			
			// aapt resource value: 0x7f0a0049
			public const int notification_main_column_container = 2131361865;
			
			// aapt resource value: 0x7f0a0058
			public const int playButton = 2131361880;
			
			// aapt resource value: 0x7f0a0059
			public const int removeButton = 2131361881;
			
			// aapt resource value: 0x7f0a0015
			public const int resolutionSpinner = 2131361813;
			
			// aapt resource value: 0x7f0a0050
			public const int right_icon = 2131361872;
			
			// aapt resource value: 0x7f0a004b
			public const int right_side = 2131361867;
			
			// aapt resource value: 0x7f0a003d
			public const int saveButton = 2131361853;
			
			// aapt resource value: 0x7f0a0019
			public const int saveVideoButton = 2131361817;
			
			// aapt resource value: 0x7f0a0039
			public const int savedButton = 2131361849;
			
			// aapt resource value: 0x7f0a0056
			public const int savedVideos = 2131361878;
			
			// aapt resource value: 0x7f0a0009
			public const int standard = 2131361801;
			
			// aapt resource value: 0x7f0a0046
			public const int status_bar_latest_event_content = 2131361862;
			
			// aapt resource value: 0x7f0a0002
			public const int text = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int text2 = 2131361795;
			
			// aapt resource value: 0x7f0a002a
			public const int text_headline = 2131361834;
			
			// aapt resource value: 0x7f0a004c
			public const int time = 2131361868;
			
			// aapt resource value: 0x7f0a0004
			public const int title = 2131361796;
			
			// aapt resource value: 0x7f0a0013
			public const int titleTextView = 2131361811;
			
			// aapt resource value: 0x7f0a0038
			public const int titleView = 2131361848;
			
			// aapt resource value: 0x7f0a0036
			public const int topBar = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int updateButton = 2131361847;
			
			// aapt resource value: 0x7f0a0016
			public const int videoTypeSpinner = 2131361814;
			
			// aapt resource value: 0x7f0a0055
			public const int videoView = 2131361877;
			
			// aapt resource value: 0x7f0a002d
			public const int view_header = 2131361837;
			
			// aapt resource value: 0x7f0a003b
			public const int webView = 2131361851;
			
			// aapt resource value: 0x7f0a0031
			public const int web_update_details = 2131361841;
			
			// aapt resource value: 0x7f0a000a
			public const int wide = 2131361802;
			
			// aapt resource value: 0x7f0a0021
			public const int wrapper_attachments = 2131361825;
			
			// aapt resource value: 0x7f0a001c
			public const int wrapper_feedback = 2131361820;
			
			// aapt resource value: 0x7f0a001b
			public const int wrapper_feedback_scroll = 2131361819;
			
			// aapt resource value: 0x7f0a0024
			public const int wrapper_messages = 2131361828;
			
			// aapt resource value: 0x7f0a0026
			public const int wrapper_messages_buttons = 2131361830;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040001
			public const int cancel_button_image_alpha = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int google_play_services_version = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int status_bar_notification_info_maxnum = 2130968578;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DownloadItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DownloadVideoView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int hockeyapp_activity_expiry_info = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int hockeyapp_activity_feedback = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int hockeyapp_activity_login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int hockeyapp_fragment_update = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int hockeyapp_view_feedback_message = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Home = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_action = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_action_tombstone = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_media_action = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_media_cancel_action = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_big_media = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_big_media_custom = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_big_media_narrow = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_big_media_narrow_custom = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int notification_template_custom_big = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int notification_template_icon_group = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int notification_template_lines_media = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int notification_template_media = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int notification_template_media_custom = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int notification_template_part_chronometer = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int notification_template_part_time = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Player = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int SavedVideos = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int VideoItem = 2130903065;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05006f
			public const int app_name = 2131034223;
			
			// aapt resource value: 0x7f050072
			public const int audio_bitrade = 2131034226;
			
			// aapt resource value: 0x7f050073
			public const int audio_type = 2131034227;
			
			// aapt resource value: 0x7f050076
			public const int available = 2131034230;
			
			// aapt resource value: 0x7f050078
			public const int cannot_download = 2131034232;
			
			// aapt resource value: 0x7f05007a
			public const int cannot_download_audio = 2131034234;
			
			// aapt resource value: 0x7f050079
			public const int cannot_download_video = 2131034233;
			
			// aapt resource value: 0x7f05007b
			public const int cannot_remove_video = 2131034235;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_button = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_enable_title = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_button = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_install_title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_notification_ticker = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_unknown_issue = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_unsupported_text = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_button = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_text = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_update_title = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_updating_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_wear_update_text = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_open_on_phone = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_signin_button_text_long = 2131034128;
			
			// aapt resource value: 0x7f050019
			public const int hockeyapp_crash_dialog_app_name_fallback = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int hockeyapp_crash_dialog_message = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int hockeyapp_crash_dialog_negative_button = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int hockeyapp_crash_dialog_neutral_button = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int hockeyapp_crash_dialog_positive_button = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int hockeyapp_crash_dialog_title = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int hockeyapp_dialog_error_message = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int hockeyapp_dialog_error_title = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int hockeyapp_dialog_positive_button = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int hockeyapp_download_failed_dialog_message = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int hockeyapp_download_failed_dialog_negative_button = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int hockeyapp_download_failed_dialog_positive_button = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int hockeyapp_download_failed_dialog_title = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int hockeyapp_error_install_form_unknown_sources_disabled = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int hockeyapp_error_no_external_storage_permission = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int hockeyapp_error_no_network_message = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int hockeyapp_expiry_info_text = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int hockeyapp_expiry_info_title = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int hockeyapp_feedback_attach_file = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int hockeyapp_feedback_attach_picture = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int hockeyapp_feedback_attachment_added = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int hockeyapp_feedback_attachment_button_text = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int hockeyapp_feedback_attachment_error = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int hockeyapp_feedback_attachment_loading = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int hockeyapp_feedback_attachment_remove_description = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int hockeyapp_feedback_attachment_removed = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int hockeyapp_feedback_email_hint = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int hockeyapp_feedback_email_hint_required = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int hockeyapp_feedback_fetching_feedback_text = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int hockeyapp_feedback_last_updated_text = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int hockeyapp_feedback_max_attachments_allowed = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int hockeyapp_feedback_message_hint = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int hockeyapp_feedback_message_hint_required = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int hockeyapp_feedback_name_hint = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int hockeyapp_feedback_name_hint_required = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int hockeyapp_feedback_new_answer_notification_message = 2131034172;
			
			// aapt resource value: 0x7f05006d
			public const int hockeyapp_feedback_notification_channel = 2131034221;
			
			// aapt resource value: 0x7f05003d
			public const int hockeyapp_feedback_notification_title = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int hockeyapp_feedback_refresh_button_text = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int hockeyapp_feedback_response_button_text = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int hockeyapp_feedback_screenshot_fail = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int hockeyapp_feedback_screenshot_notification_message = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int hockeyapp_feedback_select_file = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int hockeyapp_feedback_select_picture = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int hockeyapp_feedback_send_button_text = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int hockeyapp_feedback_send_generic_error = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int hockeyapp_feedback_send_network_error = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int hockeyapp_feedback_sending_feedback_text = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int hockeyapp_feedback_sent_toast = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int hockeyapp_feedback_subject_hint = 2131034185;
			
			// aapt resource value: 0x7f05004a
			public const int hockeyapp_feedback_subject_hint_required = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int hockeyapp_feedback_title = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int hockeyapp_feedback_validate_email_empty = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int hockeyapp_feedback_validate_email_error = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int hockeyapp_feedback_validate_name_error = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int hockeyapp_feedback_validate_subject_error = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int hockeyapp_feedback_validate_text_error = 2131034192;
			
			// aapt resource value: 0x7f050051
			public const int hockeyapp_login_email_hint_required = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int hockeyapp_login_headline_text = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int hockeyapp_login_headline_text_email_only = 2131034195;
			
			// aapt resource value: 0x7f050054
			public const int hockeyapp_login_login_button_text = 2131034196;
			
			// aapt resource value: 0x7f050055
			public const int hockeyapp_login_missing_credentials_toast = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int hockeyapp_login_password_hint_required = 2131034198;
			
			// aapt resource value: 0x7f050057
			public const int hockeyapp_paint_dialog_message = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int hockeyapp_paint_dialog_negative_button = 2131034200;
			
			// aapt resource value: 0x7f050059
			public const int hockeyapp_paint_dialog_neutral_button = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int hockeyapp_paint_dialog_positive_button = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int hockeyapp_paint_indicator_toast = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int hockeyapp_paint_menu_clear = 2131034204;
			
			// aapt resource value: 0x7f05005d
			public const int hockeyapp_paint_menu_save = 2131034205;
			
			// aapt resource value: 0x7f05005e
			public const int hockeyapp_paint_menu_undo = 2131034206;
			
			// aapt resource value: 0x7f05005f
			public const int hockeyapp_update_already_installed = 2131034207;
			
			// aapt resource value: 0x7f050060
			public const int hockeyapp_update_button = 2131034208;
			
			// aapt resource value: 0x7f050061
			public const int hockeyapp_update_dialog_message = 2131034209;
			
			// aapt resource value: 0x7f050062
			public const int hockeyapp_update_dialog_negative_button = 2131034210;
			
			// aapt resource value: 0x7f050063
			public const int hockeyapp_update_dialog_positive_button = 2131034211;
			
			// aapt resource value: 0x7f050064
			public const int hockeyapp_update_dialog_title = 2131034212;
			
			// aapt resource value: 0x7f050065
			public const int hockeyapp_update_loading = 2131034213;
			
			// aapt resource value: 0x7f050066
			public const int hockeyapp_update_mandatory_toast = 2131034214;
			
			// aapt resource value: 0x7f050067
			public const int hockeyapp_update_newest_version = 2131034215;
			
			// aapt resource value: 0x7f050068
			public const int hockeyapp_update_no_info = 2131034216;
			
			// aapt resource value: 0x7f050069
			public const int hockeyapp_update_restore = 2131034217;
			
			// aapt resource value: 0x7f05006a
			public const int hockeyapp_update_title = 2131034218;
			
			// aapt resource value: 0x7f05006b
			public const int hockeyapp_update_unknown_size = 2131034219;
			
			// aapt resource value: 0x7f05006c
			public const int hockeyapp_update_version = 2131034220;
			
			// aapt resource value: 0x7f05006e
			public const int hockeyapp_update_version_details_label = 2131034222;
			
			// aapt resource value: 0x7f050018
			public const int library_name = 2131034136;
			
			// aapt resource value: 0x7f050081
			public const int no = 2131034241;
			
			// aapt resource value: 0x7f05007c
			public const int no_internet = 2131034236;
			
			// aapt resource value: 0x7f05007d
			public const int no_videos = 2131034237;
			
			// aapt resource value: 0x7f05007e
			public const int remove_video_message = 2131034238;
			
			// aapt resource value: 0x7f05007f
			public const int remove_video_title = 2131034239;
			
			// aapt resource value: 0x7f050070
			public const int resolution = 2131034224;
			
			// aapt resource value: 0x7f050011
			public const int s1 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int s2 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int s3 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int s4 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int s5 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int s6 = 2131034134;
			
			// aapt resource value: 0x7f050074
			public const int save_audio = 2131034228;
			
			// aapt resource value: 0x7f050075
			public const int save_video = 2131034229;
			
			// aapt resource value: 0x7f050077
			public const int saved_videos = 2131034231;
			
			// aapt resource value: 0x7f050017
			public const int status_bar_notification_info_overflow = 2131034135;
			
			// aapt resource value: 0x7f050071
			public const int video_type = 2131034225;
			
			// aapt resource value: 0x7f050080
			public const int yes = 2131034240;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f07000d
			public const int HockeyApp_ButtonStyle = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int HockeyApp_EditTextStyle = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int HockeyApp_SingleLineInputStyle = 2131165199;
			
			// aapt resource value: 0x7f070006
			public const int TextAppearance_Compat_Notification = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int TextAppearance_Compat_Notification_Info = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int TextAppearance_Compat_Notification_Info_Media = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int TextAppearance_Compat_Notification_Line2 = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int TextAppearance_Compat_Notification_Media = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int TextAppearance_Compat_Notification_Time = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int TextAppearance_Compat_Notification_Time_Media = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int TextAppearance_Compat_Notification_Title = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int TextAppearance_Compat_Notification_Title_Media = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int Theme_IAPTheme = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int Widget_Compat_NotificationActionContainer = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int Widget_Compat_NotificationActionText = 2131165195;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] FontFamily = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
